language: node_js
node_js:
- "11"
addons:
  chrome: stable
install:
- rm -rf node_modules/
- npm install
jobs:
  include:
  - stage: code-tests
    script:
    - npm run lint
    - |
      if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
        echo "Pull request with secure environment variables, running Sauce tests...";
        npm run test:polymer:sauce || travis_terminate 1;
      else
        echo "Not a pull request and/or no secure environment variables, running headless tests...";
        npm run test:polymer:local || travis_terminate 1;
      fi
    - npm run test:js
  - stage: visual-difference-tests
    script:
    - |
      if [ $TRAVIS_SECURE_ENV_VARS == true ]; then
        echo "Running visual difference tests...";
        npm run test:diff || travis_terminate 1;
      fi
  - stage: update-version
    script: frauci-update-version && export TRAVIS_TAG=$(frauci-get-version)
deploy:
  provider: releases
  api_key: "$GITHUB_RELEASE_TOKEN"
  on:
    tags: true
notifications:
  email:
    recipients:
      - Alex.Bedley@D2L.com
env:
  global:
  - OWNER_NAME: Brightspacehypermediacomponents
  - REPO_NAME: activities
  - DEFAULT_INCREMENT: patch
  - SAUCE_USERNAME: Desire2Learn
  # SAUCE_ACCESS_KEY
  - secure: uI1bP8ViYhpBhMczmiqmDowwG5cqmqL1xr+RGRwbqxQiTbnDcGI77H/DEnbuKDYcSMZ/a4qqwN1DMoUWmD+n23oxUKSDr6dR0tP/6++Y0wykPU+79UX4SdTM2UvW4arcsU9Yy7MG7H+HsM8IaHqDUw+V/hIThK0/axE9qEUZyb2s3IQSbt6sJxDvFDlyeqMny9VABlV/PIG4IPJ4PsWPjSVFGAWUPE+64h2STxvRixd8DI6n53PqGZEXl5huWgKosfnmXS+S37gjGJXJmZj/kCLvvAoQi3L6k/Hlf/8QwCdnHkCjN8In8I278S+zBGQsBMhxUVuTbbUbNuf71oKaYutF0uYMCH+CPb7LcNbpC9sDFdxZXCLyMVQOAw38473SVXui2INxzq4lGI5Pf4PGhqh3gacg5PLg4QjDyRbI8Qx9axzn5vaFotgvW0t3ZSynNfhxOnPhUs7nQoJjhcJPRRBzGI33XSQzwZGOBLUiXrwGTyKTy6hHjGYV+EolH08mtCzXfGBdvTXbOf3e0AwNm7s00CO6ablwvtdSzfRDnKX0A+rMlbcJZp+4gTiqZV/jLMXTUoyteeZ6hn2C04z7xh0BiytpcW+Nx1VkCVr6JukgtzzA5HQAMub7ofklGvkACYn/IWATPlItMgRFg1Wydy6d4n3qSts50Qmyhq1W1NM=
  # GITHUB_RELEASE_TOKEN (859f......865e)
  - secure: QP5YZ7oT1NAyyLDhNG/kHii+SasV5zR/9XO5ePl2ThAevdpEgrLLk1A76NV0XZMMSRIdvgzMZIvPqHWfA81I2O7QCzXOJKQ+xj8hanGqUUNlGxgDMo8FGmqf7OWyxw+XHoM5E0P20yntmDQnCsYnuPvTwYyZ/6ujQgTbPli2ewvoZL+Doh+RnOHmc7R8HbdpU2Cv42PIZr/H/nW6tpuliP1fNrMvKwzjbRu+zh/ag62CkPOk0jbu6klXTwdwytb0jseY7Y/ybJ/0kOZGmgCguH3Lb2kj4Uncp78aQiAZFyCIurb6iXVZ5K7YtABbpWj2sRtMkJwQedTSCUY7PI8FTuvNowZ9URmJ5d4FAAbo03D6jgur4SHxakyV+iQj5z0vfmw5bJT/ykJzXFgyRTkjy/zznZE3arDeyRiLPKGmlKSYDS51eXUhJ2yqgFtsw3ArCqIoIm3xxe9Qy2DNsJllf/SGIhcGhPXIlG4Mj/59OiqNVJuXORJkwuj4SNK4ujkTGkHWYgwGEglhF9nCSPBOrITaFtyfECNvHc9HM/SeYyaDjMqrvXnGusoU6BKhxqiwhb2LhqrK9SRq6ibeP9ykjvi3PkrmbyVHKTAzXHxKJ5uS1orwQ7oOnC4p751pjZB570wIg4ENUsPML/EwbtfsqWjCYnzGZqOgP8mYDXDprr8=
  # VISUAL_DIFF_S3_ID
  - secure: dHkipUhiVlFjaI2Lm+xxJU/HB+YTyJYjsmrAkfF244xa0cSLsH3uLI7R0sQwaBJQ1nAMOzHRqCovNBD55oPKTa8DxC7nU9hHtP4WIxiSKY0NQlGVR2f4Diecgzdv60oKC43Bf899ojBttiH6QRuntqM++HTx41rnhcwIg+3/POceO6TW0XQMaD8NNJgcRUNQQOayAGtfFSa1Zw8XEVlo58f1icwtTsB6PSYxN7rQjsJdA8Tga/1qPxG/iLLHcTvtbpdh+fQ5h/kKizBuLnVp1x0rh9UCOSOlTKPUgHGkvDBDg89LvJdjk4VchbhHbZBA0ge3o4T/wzeXYblYMyevNJoT/0JzaoNS1M8yWKQAy4LWUTG/At8qo9W8GwXowAEnaKAzMB8dbmq6HgnKE7SiWOOlT+U9a9zP+y90GoeLURmhwa6ZHhFSl/JqmE64sKvhBahTpqC7ZxBty65u+D75smf/LNv/DZAkX9OMiLbO2D81D4DlJuNy/7p0ze3yGA4rlCc1q+qlwm9Kjwa0+quU5Y3yy7+SG/hDvJHDTX0QPu62bR0adFuXzdqRyg1KJhc/7ZXyKzaBTNV0qhy20ync8P3xcGWhSdXZPWHX7NKIbUp7WugiS4XZt5eRB6/5bE9Bk5H92/sgnbsdhVjG2rhxUE9NO0HGBRNDznowdAOhHys=
  # VISUAL_DIFF_S3_SECRET
  - secure: 0AHHbpi7AkVAiSAGfts62biGzGq21cVzYhM7ko0Iqi/WO/Yi14WlZb6Oz9OVhJB8AqrVCxBVxSHmKYZo/WU9HD25qcTRJGvRiXfWB2j3f7BBTdjv9/YuS5dQNEC+Xhr2aRP0nVLMnXZvsXJY4aZu7/BZBSZctvSXe3xKHS6J8wajoirtxcCCld9T8vC0qDen0D+Qh5NAKsAnPOUW56vTT2AAir3rFRpUy68+yY8lvXIKfxBLrbQwtbDjfyLQux8bZdVfY6V0hph1qimFqXr+yCo0tn58jupfja4nIFnYW4mzL/c1eWEx2xMPjzPu6AkFFXUbrWI8jKcDdacyhHL0QyxV0WbOYOG5jBdqfsFsKik/6rU7g02lU6E8Ud7jenISxxmzv8BRmFUikaxapRlrqhTDS+3DgljjswPiNmAfixeLtkfyeyS/DvXdAFYor6kZ78ZR8FDAbxLizaCao5GTv1KkiN8w2ixWxgw7QuP2+TQnpbXV0atiN/QcsdSahsKzmWHqWYW8JIS+QAeZyygsHhOiH6zp7h6pzd3DyEz8+kMk9wUj8TwXCA47uyx0EwsP6oA86jIzOrVPujvJyR5zmmRU/ForZdy6UTSFfRAZ5Bve8Y67mtq5G9/9RXU5LLp0vKiCzCAZCPStAFdxvQ0YM0y0Fih8iaWyPHxZO1joGoo=
