language: node_js
node_js:
- "11"
addons:
  chrome: stable
install:
- npm install
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:polymer:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:polymer:local || travis_terminate 1;
  fi
env:
  global:
  - SAUCE_USERNAME: Desire2Learn
  - secure: uI1bP8ViYhpBhMczmiqmDowwG5cqmqL1xr+RGRwbqxQiTbnDcGI77H/DEnbuKDYcSMZ/a4qqwN1DMoUWmD+n23oxUKSDr6dR0tP/6++Y0wykPU+79UX4SdTM2UvW4arcsU9Yy7MG7H+HsM8IaHqDUw+V/hIThK0/axE9qEUZyb2s3IQSbt6sJxDvFDlyeqMny9VABlV/PIG4IPJ4PsWPjSVFGAWUPE+64h2STxvRixd8DI6n53PqGZEXl5huWgKosfnmXS+S37gjGJXJmZj/kCLvvAoQi3L6k/Hlf/8QwCdnHkCjN8In8I278S+zBGQsBMhxUVuTbbUbNuf71oKaYutF0uYMCH+CPb7LcNbpC9sDFdxZXCLyMVQOAw38473SVXui2INxzq4lGI5Pf4PGhqh3gacg5PLg4QjDyRbI8Qx9axzn5vaFotgvW0t3ZSynNfhxOnPhUs7nQoJjhcJPRRBzGI33XSQzwZGOBLUiXrwGTyKTy6hHjGYV+EolH08mtCzXfGBdvTXbOf3e0AwNm7s00CO6ablwvtdSzfRDnKX0A+rMlbcJZp+4gTiqZV/jLMXTUoyteeZ6hn2C04z7xh0BiytpcW+Nx1VkCVr6JukgtzzA5HQAMub7ofklGvkACYn/IWATPlItMgRFg1Wydy6d4n3qSts50Qmyhq1W1NM=
